// Mocks generated by Mockito 5.3.2 from annotations
// in office_booking_app/test/model/building/api/building_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:office_booking_app/model/building/api/building_api.dart' as _i3;
import 'package:office_booking_app/model/building/building_detail_model.dart'
    as _i2;
import 'package:office_booking_app/model/building/building_model.dart' as _i5;
import 'package:office_booking_app/model/reservation/rating_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBuildingDetailModel_0 extends _i1.SmartFake
    implements _i2.BuildingDetailModel {
  _FakeBuildingDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BuildingApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildingApi extends _i1.Mock implements _i3.BuildingApi {
  MockBuildingApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.BuildingModel>> getAllBuildings() => (super.noSuchMethod(
        Invocation.method(
          #getAllBuildings,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.BuildingModel>>.value(<_i5.BuildingModel>[]),
      ) as _i4.Future<List<_i5.BuildingModel>>);
  @override
  _i4.Future<_i2.BuildingDetailModel> getBuildingDetail(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuildingDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.BuildingDetailModel>.value(
            _FakeBuildingDetailModel_0(
          this,
          Invocation.method(
            #getBuildingDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.BuildingDetailModel>);
  @override
  _i4.Future<List<_i6.RatingModel>> getReview(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReview,
          [id],
        ),
        returnValue:
            _i4.Future<List<_i6.RatingModel>>.value(<_i6.RatingModel>[]),
      ) as _i4.Future<List<_i6.RatingModel>>);
}
